# Jekyll Configuration to force compiling files starting with underscores
include:
  - "setup/_OS_Dev_Setting.md"
  - "setup/_LM_Studio_Pi_Coding_Agent.md"
  - "antigravity/_antigravity_cli.md"
  - "docker/_docker_remote_dev_env.md"
  - "docker/_docker_container_setup.md"
  - "docker/_docker_management_ops.md"
  - "docs/_github.md"
  - "docs/_github_actions.md"
  - "docs/_venv.md"
